package com.example.foodster.pojo

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity("mealInformation")
data class Meal(
    val dateModified: Any?,
    @PrimaryKey
    val idMeal: String,
    val strArea: String?,
    val strCategory: String?,
    val strCreativeCommonsConfirmed: Any?,
    val strDrinkAlternate: Any?,
    val strImageSource: Any?,
    val Stringredient1: String?,
    val Stringredient10: String?,
    val Stringredient11: String?,
    val Stringredient12: String?,
    val Stringredient13: String?,
    val Stringredient14: String?,
    val Stringredient15: String?,
    val Stringredient16: String?,
    val Stringredient17: String?,
    val Stringredient18: String?,
    val Stringredient19: String?,
    val Stringredient2: String?,
    val Stringredient20: String?,
    val Stringredient3: String?,
    val Stringredient4: String?,
    val Stringredient5: String?,
    val Stringredient6: String?,
    val Stringredient7: String?,
    val Stringredient8: String?,
    val Stringredient9: String?,
    val strInstructions: String?,
    val strMeal: String?,
    val strMealThumb: String?,
    val strMeasure1: String?,
    val strMeasure10: String?,
    val strMeasure11: String?,
    val strMeasure12: String?,
    val strMeasure13: String?,
    val strMeasure14: String?,
    val strMeasure15: String?,
    val strMeasure16: String?,
    val strMeasure17: String?,
    val strMeasure18: String?,
    val strMeasure19: String?,
    val strMeasure2: String?,
    val strMeasure20: String?,
    val strMeasure3: String?,
    val strMeasure4: String?,
    val strMeasure5: String?,
    val strMeasure6: String?,
    val strMeasure7: String?,
    val strMeasure8: String?,
    val strMeasure9: String?,
    val strSource: String?,
    val strTags: String?,
    val strYoutube: String?
)